apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
# everything is assumed to be in base64
# to get this value, run: cat ~/.ssh/id_ed25519 | base64 (assuming you have an id_ed25519 key in the default location) and the same for known_hosts and config
  id_rsa: AS0tLS...
  or 
  id_ed25519: Acads...
  known_hosts: AG033S...
  config: GS0FFL...